### ISSUE TITLE
Experiment with ECE placement and configuration

### ISSUE THREAD

**Issue by quaeler** [tlaplus/tlaplus#288]
Experiment with ECE potentially being on its own tab; also, consider providing a widget which drops the execution in and out of 'no behavior spec' mode.

**Comment by lemmy** [comment]
A preference could allow users to switch between the ECE on the Result Page and a dedicated tab.  It would probably make sense to split the "TLC model checker" preference page into a TLC related and a Model Editor related page.

**Comment by lemmy** [comment]
Stretch goal for 1.5.8

**Comment by quaeler** [comment]
I'm not sure it makes sense to split up the preference page - there's not much there now, and if we split it out, the resulting TLC-specific page would have only two items (the ones not highlighted in this ss)

<img width="638" alt="model_checker_preference_page" src="https://user-images.githubusercontent.com/22581048/58838160-c722f100-8612-11e9-8560-1ce9357bdf5e.png">

**Comment by lemmy** [comment]
Lets leave it as-is for now.

**Comment by quaeler** [comment]
This has been implemented; it's been placid for a couple days now so i am closing the issue.

**Comment by lemmy** [comment]
I suggest to adjust the tab's title from "Evaluate ConEx" to "Constant Expressions".  The "No Evaluation" button should be changed to a check-box called "No Behavior Spec" to be consistent with the main model page.

**Comment by quaeler** [comment]
Tab title seems fine.

... but the button change makes me flinch; here's the opportunity to introduce some common semantic notions to what seems obscured by "No Behavior Spec".
Yes: NBS is technically correct, but for a user who wants to think in terms of 'will i be evaluating or won't i be evaluating' this synonym replacement feels awkward.

**Comment by lemmy** [comment]
It is unclear what will be evaluated with "Will evaluate": The ECE expression is in both cases evaluated, the spec with "No Evaluation".  Isn't this then upside-down?

One more thing: With "Will evaluate" and ECE as dedicated tab, running TLC switches to the Result Page.

**Comment by quaeler** [comment]
Hmm.. the switch to "don't switch to the result page" was addressed previously; will look to see what broke it.

I forgot that the ECE will get evaluated even if it's not NBS; i'll change the button type and text.  (Traditionally a toggle switch reads as what it's current state is, not what it will become when you push it.. in both the real world (a light switch that says off when it's on?) and the rendered world.)

**Comment by quaeler** [comment]
Addressed with c4cde58bcab0b2342b080d247e5f33eb70ad993b - will close this ticket in a couple days if no further issues are raised.

**Comment by lemmy** [comment]
Buttons and labels look good now.  "Switch to Result Page" bug still present if c4cde58 is supposed to fix it.

**Comment by lemmy** [comment]
```TLA_Functional_ECE_Placement``` has to be updated to the new labels and button change:

```
Regression

TEST-org.lamport.tla.toolbox.product.uitest.TLA_Functional_ECE_Placement
Failing for the past 1 build (Since Unstable#184 )
Took 16 sec.
add description
Error Message

Line 36: get-tab-item: The TabItem "Evaluate ConEx" could not be found.  

Stacktrace

Line 36: get-tab-item: The TabItem "Evaluate ConEx" could not be found.  data=[B@66f18fa
    message=The TabItem "Evaluate ConEx" could not be found.(TLA+ Toolbox)

  Info in plugin: org.eclipse.rcptt.ecl.platform
  message: project new [ new.tla ]
```

**Comment by quaeler** [comment]
Marking this issue as closed as i think it is now hashed-out. Please re-open if not though.
